"""Add counts to DatasetImport

Revision ID: ca1c2ccc9e79
Revises: 'f436ed47faec'
Create Date: 2026-08-29 15:01:55.293669

"""
from typing import Sequence, Union
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = 'ca1c2ccc9e79'
down_revision: Union[str, None] = 'f436ed47faec'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('dataset_imports', sa.Column('accepted_count', sa.Integer(), nullable=False, server_default='0'))
    op.add_column('dataset_imports', sa.Column('quarantined_count', sa.Integer(), nullable=False, server_default='0'))
    op.add_column('dataset_imports', sa.Column('processing_duration_seconds', sa.Float(), nullable=True))
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('dataset_imports', 'processing_duration_seconds')
    op.drop_column('dataset_imports', 'quarantined_count')
    op.drop_column('dataset_imports', 'accepted_count')
    # ### end Alembic commands ###
