"""Initial 20 entities migration

Revision ID: f436ed47faec
Revises: None
Create Date: 2026-08-29 14:53:06.667911

"""
from typing import Sequence, Union
from alembic import op
import sqlalchemy as sa
import app.models.base


# revision identifiers, used by Alembic.
revision: str = 'f436ed47faec'
down_revision: Union[str, None] = None
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('cses',
    sa.Column('id', app.models.base.GUID(length=36), nullable=False),
    sa.Column('name', sa.String(length=255), nullable=False),
    sa.Column('sector', sa.String(length=100), nullable=False),
    sa.Column('entity_type', sa.String(length=100), nullable=False),
    sa.Column('size_tier', sa.String(length=50), nullable=False),
    sa.Column('metadata_json', sa.JSON(), nullable=True),
    sa.Column('created_at', sa.DateTime(timezone=True), nullable=False),
    sa.Column('updated_at', sa.DateTime(timezone=True), nullable=False),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_cses_created_at'), 'cses', ['created_at'], unique=False)
    op.create_index(op.f('ix_cses_entity_type'), 'cses', ['entity_type'], unique=False)
    op.create_index(op.f('ix_cses_name'), 'cses', ['name'], unique=True)
    op.create_index(op.f('ix_cses_sector'), 'cses', ['sector'], unique=False)
    op.create_table('dataset_imports',
    sa.Column('id', app.models.base.GUID(length=36), nullable=False),
    sa.Column('filename', sa.String(length=255), nullable=False),
    sa.Column('source', sa.String(length=100), nullable=False),
    sa.Column('imported_at', sa.DateTime(timezone=True), nullable=False),
    sa.Column('imported_by', sa.String(length=100), nullable=False),
    sa.Column('row_count', sa.Integer(), nullable=False),
    sa.Column('status', sa.Enum('PENDING', 'PROCESSING', 'COMPLETED', 'FAILED', 'QUARANTINED', name='datasetimportstatus', native_enum=False), nullable=False),
    sa.Column('completeness_score', sa.Float(), nullable=False),
    sa.Column('created_at', sa.DateTime(timezone=True), nullable=False),
    sa.Column('updated_at', sa.DateTime(timezone=True), nullable=False),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_dataset_imports_created_at'), 'dataset_imports', ['created_at'], unique=False)
    op.create_index(op.f('ix_dataset_imports_imported_at'), 'dataset_imports', ['imported_at'], unique=False)
    op.create_index(op.f('ix_dataset_imports_status'), 'dataset_imports', ['status'], unique=False)
    op.create_table('model_versions',
    sa.Column('id', app.models.base.GUID(length=36), nullable=False),
    sa.Column('model_name', sa.String(length=100), nullable=False),
    sa.Column('version', sa.String(length=50), nullable=False),
    sa.Column('trained_at', sa.DateTime(timezone=True), nullable=False),
    sa.Column('training_dataset_ref', sa.String(length=255), nullable=True),
    sa.Column('metrics_json', sa.JSON(), nullable=True),
    sa.Column('status', sa.Enum('ACTIVE', 'DEPRECATED', 'DRAFT', name='versionstatus', native_enum=False), nullable=False),
    sa.Column('packaged_path', sa.String(length=512), nullable=True),
    sa.Column('created_at', sa.DateTime(timezone=True), nullable=False),
    sa.Column('updated_at', sa.DateTime(timezone=True), nullable=False),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('model_name', 'version', name='uq_model_version')
    )
    op.create_index(op.f('ix_model_versions_created_at'), 'model_versions', ['created_at'], unique=False)
    op.create_index(op.f('ix_model_versions_model_name'), 'model_versions', ['model_name'], unique=False)
    op.create_index(op.f('ix_model_versions_status'), 'model_versions', ['status'], unique=False)
    op.create_index(op.f('ix_model_versions_version'), 'model_versions', ['version'], unique=False)
    op.create_table('peer_groups',
    sa.Column('id', app.models.base.GUID(length=36), nullable=False),
    sa.Column('name', sa.String(length=255), nullable=False),
    sa.Column('grouping_criteria', sa.JSON(), nullable=False),
    sa.Column('created_at', sa.DateTime(timezone=True), nullable=False),
    sa.Column('updated_at', sa.DateTime(timezone=True), nullable=False),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_peer_groups_created_at'), 'peer_groups', ['created_at'], unique=False)
    op.create_index(op.f('ix_peer_groups_name'), 'peer_groups', ['name'], unique=True)
    op.create_table('rule_versions',
    sa.Column('id', app.models.base.GUID(length=36), nullable=False),
    sa.Column('rule_id', sa.String(length=100), nullable=False),
    sa.Column('version', sa.String(length=50), nullable=False),
    sa.Column('name', sa.String(length=255), nullable=False),
    sa.Column('definition_json', sa.JSON(), nullable=False),
    sa.Column('status', sa.Enum('ACTIVE', 'DEPRECATED', 'DRAFT', name='versionstatus', native_enum=False), nullable=False),
    sa.Column('created_by', sa.String(length=100), nullable=False),
    sa.Column('created_at', sa.DateTime(timezone=True), nullable=False),
    sa.Column('updated_at', sa.DateTime(timezone=True), nullable=False),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('rule_id', 'version', name='uq_rule_version')
    )
    op.create_index(op.f('ix_rule_versions_created_at'), 'rule_versions', ['created_at'], unique=False)
    op.create_index(op.f('ix_rule_versions_rule_id'), 'rule_versions', ['rule_id'], unique=False)
    op.create_index(op.f('ix_rule_versions_status'), 'rule_versions', ['status'], unique=False)
    op.create_index(op.f('ix_rule_versions_version'), 'rule_versions', ['version'], unique=False)
    op.create_table('analysis_runs',
    sa.Column('id', app.models.base.GUID(length=36), nullable=False),
    sa.Column('dataset_import_id', app.models.base.GUID(length=36), nullable=False),
    sa.Column('rule_version_id', app.models.base.GUID(length=36), nullable=True),
    sa.Column('model_version_id', app.models.base.GUID(length=36), nullable=True),
    sa.Column('started_at', sa.DateTime(timezone=True), nullable=False),
    sa.Column('ended_at', sa.DateTime(timezone=True), nullable=True),
    sa.Column('status', sa.Enum('PENDING', 'RUNNING', 'COMPLETED', 'FAILED', name='analysisrunstatus', native_enum=False), nullable=False),
    sa.Column('records_processed', sa.Integer(), nullable=False),
    sa.Column('findings_generated', sa.Integer(), nullable=False),
    sa.Column('rule_version', sa.String(length=50), nullable=False),
    sa.Column('model_version', sa.String(length=50), nullable=False),
    sa.Column('configuration', sa.JSON(), nullable=True),
    sa.Column('processing_duration_seconds', sa.Float(), nullable=True),
    sa.Column('created_at', sa.DateTime(timezone=True), nullable=False),
    sa.Column('updated_at', sa.DateTime(timezone=True), nullable=False),
    sa.ForeignKeyConstraint(['dataset_import_id'], ['dataset_imports.id'], ondelete='CASCADE'),
    sa.ForeignKeyConstraint(['model_version_id'], ['model_versions.id'], ondelete='SET NULL'),
    sa.ForeignKeyConstraint(['rule_version_id'], ['rule_versions.id'], ondelete='SET NULL'),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_analysis_runs_created_at'), 'analysis_runs', ['created_at'], unique=False)
    op.create_index(op.f('ix_analysis_runs_dataset_import_id'), 'analysis_runs', ['dataset_import_id'], unique=False)
    op.create_index(op.f('ix_analysis_runs_model_version_id'), 'analysis_runs', ['model_version_id'], unique=False)
    op.create_index(op.f('ix_analysis_runs_rule_version_id'), 'analysis_runs', ['rule_version_id'], unique=False)
    op.create_index(op.f('ix_analysis_runs_started_at'), 'analysis_runs', ['started_at'], unique=False)
    op.create_index(op.f('ix_analysis_runs_status'), 'analysis_runs', ['status'], unique=False)
    op.create_table('analysts',
    sa.Column('id', app.models.base.GUID(length=36), nullable=False),
    sa.Column('cse_id', app.models.base.GUID(length=36), nullable=False),
    sa.Column('handle', sa.String(length=100), nullable=False),
    sa.Column('role', sa.String(length=100), nullable=False),
    sa.Column('created_at', sa.DateTime(timezone=True), nullable=False),
    sa.Column('updated_at', sa.DateTime(timezone=True), nullable=False),
    sa.ForeignKeyConstraint(['cse_id'], ['cses.id'], ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index('idx_analyst_cse_handle', 'analysts', ['cse_id', 'handle'], unique=True)
    op.create_index(op.f('ix_analysts_created_at'), 'analysts', ['created_at'], unique=False)
    op.create_index(op.f('ix_analysts_cse_id'), 'analysts', ['cse_id'], unique=False)
    op.create_table('assets',
    sa.Column('id', app.models.base.GUID(length=36), nullable=False),
    sa.Column('cse_id', app.models.base.GUID(length=36), nullable=False),
    sa.Column('name', sa.String(length=255), nullable=False),
    sa.Column('asset_type', sa.String(length=100), nullable=False),
    sa.Column('criticality', sa.Enum('CRITICAL', 'HIGH', 'MEDIUM', 'LOW', name='assetcriticality', native_enum=False), nullable=False),
    sa.Column('status', sa.String(length=50), nullable=False),
    sa.Column('decommissioned_at', sa.DateTime(timezone=True), nullable=True),
    sa.Column('created_at', sa.DateTime(timezone=True), nullable=False),
    sa.Column('updated_at', sa.DateTime(timezone=True), nullable=False),
    sa.ForeignKeyConstraint(['cse_id'], ['cses.id'], ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index('idx_asset_cse_criticality', 'assets', ['cse_id', 'criticality'], unique=False)
    op.create_index(op.f('ix_assets_created_at'), 'assets', ['created_at'], unique=False)
    op.create_index(op.f('ix_assets_criticality'), 'assets', ['criticality'], unique=False)
    op.create_index(op.f('ix_assets_cse_id'), 'assets', ['cse_id'], unique=False)
    op.create_index(op.f('ix_assets_status'), 'assets', ['status'], unique=False)
    op.create_table('benchmarks',
    sa.Column('id', app.models.base.GUID(length=36), nullable=False),
    sa.Column('peer_group_id', app.models.base.GUID(length=36), nullable=False),
    sa.Column('metric_name', sa.String(length=100), nullable=False),
    sa.Column('median', sa.Float(), nullable=False),
    sa.Column('p25', sa.Float(), nullable=False),
    sa.Column('p75', sa.Float(), nullable=False),
    sa.Column('std_dev', sa.Float(), nullable=False),
    sa.Column('computed_at', sa.DateTime(timezone=True), nullable=False),
    sa.Column('created_at', sa.DateTime(timezone=True), nullable=False),
    sa.Column('updated_at', sa.DateTime(timezone=True), nullable=False),
    sa.ForeignKeyConstraint(['peer_group_id'], ['peer_groups.id'], ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('peer_group_id', 'metric_name', name='uq_peer_metric')
    )
    op.create_index(op.f('ix_benchmarks_created_at'), 'benchmarks', ['created_at'], unique=False)
    op.create_index(op.f('ix_benchmarks_metric_name'), 'benchmarks', ['metric_name'], unique=False)
    op.create_index(op.f('ix_benchmarks_peer_group_id'), 'benchmarks', ['peer_group_id'], unique=False)
    op.create_table('cases',
    sa.Column('id', app.models.base.GUID(length=36), nullable=False),
    sa.Column('cse_id', app.models.base.GUID(length=36), nullable=False),
    sa.Column('status', sa.String(length=50), nullable=False),
    sa.Column('opened_at', sa.DateTime(timezone=True), nullable=False),
    sa.Column('closed_at', sa.DateTime(timezone=True), nullable=True),
    sa.Column('created_at', sa.DateTime(timezone=True), nullable=False),
    sa.Column('updated_at', sa.DateTime(timezone=True), nullable=False),
    sa.ForeignKeyConstraint(['cse_id'], ['cses.id'], ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_cases_created_at'), 'cases', ['created_at'], unique=False)
    op.create_index(op.f('ix_cases_cse_id'), 'cases', ['cse_id'], unique=False)
    op.create_index(op.f('ix_cases_status'), 'cases', ['status'], unique=False)
    op.create_table('data_quality_issues',
    sa.Column('id', app.models.base.GUID(length=36), nullable=False),
    sa.Column('dataset_import_id', app.models.base.GUID(length=36), nullable=False),
    sa.Column('issue_type', sa.String(length=100), nullable=False),
    sa.Column('field', sa.String(length=100), nullable=True),
    sa.Column('record_ref', sa.String(length=255), nullable=True),
    sa.Column('severity', sa.Enum('CRITICAL', 'HIGH', 'MEDIUM', 'LOW', 'INFO', name='dataqualityseverity', native_enum=False), nullable=False),
    sa.Column('description', sa.Text(), nullable=False),
    sa.Column('created_at', sa.DateTime(timezone=True), nullable=False),
    sa.Column('updated_at', sa.DateTime(timezone=True), nullable=False),
    sa.ForeignKeyConstraint(['dataset_import_id'], ['dataset_imports.id'], ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_data_quality_issues_created_at'), 'data_quality_issues', ['created_at'], unique=False)
    op.create_index(op.f('ix_data_quality_issues_dataset_import_id'), 'data_quality_issues', ['dataset_import_id'], unique=False)
    op.create_index(op.f('ix_data_quality_issues_issue_type'), 'data_quality_issues', ['issue_type'], unique=False)
    op.create_index(op.f('ix_data_quality_issues_severity'), 'data_quality_issues', ['severity'], unique=False)
    op.create_table('peer_group_memberships',
    sa.Column('cse_id', app.models.base.GUID(length=36), nullable=False),
    sa.Column('peer_group_id', app.models.base.GUID(length=36), nullable=False),
    sa.Column('joined_at', sa.DateTime(timezone=True), nullable=False),
    sa.Column('created_at', sa.DateTime(timezone=True), nullable=False),
    sa.Column('updated_at', sa.DateTime(timezone=True), nullable=False),
    sa.ForeignKeyConstraint(['cse_id'], ['cses.id'], ondelete='CASCADE'),
    sa.ForeignKeyConstraint(['peer_group_id'], ['peer_groups.id'], ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('cse_id', 'peer_group_id')
    )
    op.create_index(op.f('ix_peer_group_memberships_created_at'), 'peer_group_memberships', ['created_at'], unique=False)
    op.create_table('alerts',
    sa.Column('id', app.models.base.GUID(length=36), nullable=False),
    sa.Column('cse_id', app.models.base.GUID(length=36), nullable=False),
    sa.Column('asset_id', app.models.base.GUID(length=36), nullable=False),
    sa.Column('source_system', sa.String(length=100), nullable=False),
    sa.Column('category', sa.String(length=100), nullable=False),
    sa.Column('severity', sa.Enum('CRITICAL', 'HIGH', 'MEDIUM', 'LOW', 'INFO', name='alertseverity', native_enum=False), nullable=False),
    sa.Column('raw_severity', sa.String(length=50), nullable=False),
    sa.Column('status', sa.String(length=50), nullable=False),
    sa.Column('created_at', sa.DateTime(timezone=True), nullable=False),
    sa.Column('updated_at', sa.DateTime(timezone=True), nullable=False),
    sa.ForeignKeyConstraint(['asset_id'], ['assets.id'], ondelete='CASCADE'),
    sa.ForeignKeyConstraint(['cse_id'], ['cses.id'], ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index('idx_alert_created_at', 'alerts', ['created_at'], unique=False)
    op.create_index('idx_alert_cse_severity_status', 'alerts', ['cse_id', 'severity', 'status'], unique=False)
    op.create_index(op.f('ix_alerts_asset_id'), 'alerts', ['asset_id'], unique=False)
    op.create_index(op.f('ix_alerts_category'), 'alerts', ['category'], unique=False)
    op.create_index(op.f('ix_alerts_created_at'), 'alerts', ['created_at'], unique=False)
    op.create_index(op.f('ix_alerts_cse_id'), 'alerts', ['cse_id'], unique=False)
    op.create_index(op.f('ix_alerts_severity'), 'alerts', ['severity'], unique=False)
    op.create_index(op.f('ix_alerts_status'), 'alerts', ['status'], unique=False)
    op.create_table('audit_logs',
    sa.Column('id', app.models.base.GUID(length=36), nullable=False),
    sa.Column('user_id', sa.String(length=100), nullable=False),
    sa.Column('action', sa.String(length=100), nullable=False),
    sa.Column('entity_type', sa.String(length=100), nullable=False),
    sa.Column('entity_id', sa.String(length=255), nullable=False),
    sa.Column('timestamp', sa.DateTime(timezone=True), nullable=False),
    sa.Column('before_after_json', sa.JSON(), nullable=True),
    sa.Column('dataset_import_id', app.models.base.GUID(length=36), nullable=True),
    sa.Column('analysis_run_id', app.models.base.GUID(length=36), nullable=True),
    sa.Column('rule_version', sa.String(length=50), nullable=True),
    sa.Column('model_version', sa.String(length=50), nullable=True),
    sa.Column('created_at', sa.DateTime(timezone=True), nullable=False),
    sa.Column('updated_at', sa.DateTime(timezone=True), nullable=False),
    sa.ForeignKeyConstraint(['analysis_run_id'], ['analysis_runs.id'], ondelete='SET NULL'),
    sa.ForeignKeyConstraint(['dataset_import_id'], ['dataset_imports.id'], ondelete='SET NULL'),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_audit_logs_action'), 'audit_logs', ['action'], unique=False)
    op.create_index(op.f('ix_audit_logs_analysis_run_id'), 'audit_logs', ['analysis_run_id'], unique=False)
    op.create_index(op.f('ix_audit_logs_created_at'), 'audit_logs', ['created_at'], unique=False)
    op.create_index(op.f('ix_audit_logs_dataset_import_id'), 'audit_logs', ['dataset_import_id'], unique=False)
    op.create_index(op.f('ix_audit_logs_entity_id'), 'audit_logs', ['entity_id'], unique=False)
    op.create_index(op.f('ix_audit_logs_entity_type'), 'audit_logs', ['entity_type'], unique=False)
    op.create_index(op.f('ix_audit_logs_timestamp'), 'audit_logs', ['timestamp'], unique=False)
    op.create_index(op.f('ix_audit_logs_user_id'), 'audit_logs', ['user_id'], unique=False)
    op.create_table('closures',
    sa.Column('id', app.models.base.GUID(length=36), nullable=False),
    sa.Column('case_id', app.models.base.GUID(length=36), nullable=False),
    sa.Column('disposition_type', sa.Enum('TRUE_POSITIVE', 'FALSE_POSITIVE', 'BENIGN_POSITIVE', 'INCONCLUSIVE', 'DUPLICATE', name='dispositiontype', native_enum=False), nullable=False),
    sa.Column('closed_by', sa.String(length=100), nullable=False),
    sa.Column('closed_at', sa.DateTime(timezone=True), nullable=False),
    sa.Column('justification', sa.Text(), nullable=True),
    sa.Column('created_at', sa.DateTime(timezone=True), nullable=False),
    sa.Column('updated_at', sa.DateTime(timezone=True), nullable=False),
    sa.ForeignKeyConstraint(['case_id'], ['cases.id'], ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_closures_case_id'), 'closures', ['case_id'], unique=True)
    op.create_index(op.f('ix_closures_created_at'), 'closures', ['created_at'], unique=False)
    op.create_table('findings',
    sa.Column('id', app.models.base.GUID(length=36), nullable=False),
    sa.Column('analysis_run_id', app.models.base.GUID(length=36), nullable=False),
    sa.Column('rule_id', sa.String(length=100), nullable=True),
    sa.Column('rule_version', sa.String(length=50), nullable=False),
    sa.Column('model_version', sa.String(length=50), nullable=True),
    sa.Column('cse_id', app.models.base.GUID(length=36), nullable=False),
    sa.Column('asset_id', app.models.base.GUID(length=36), nullable=True),
    sa.Column('case_id', app.models.base.GUID(length=36), nullable=True),
    sa.Column('severity', sa.Enum('CRITICAL', 'HIGH', 'MEDIUM', 'LOW', name='findingseverity', native_enum=False), nullable=False),
    sa.Column('anomaly_score', sa.Float(), nullable=False),
    sa.Column('confidence', sa.Float(), nullable=False),
    sa.Column('risk_score', sa.Float(), nullable=False),
    sa.Column('supervisory_priority', sa.Float(), nullable=False),
    sa.Column('reason', sa.Text(), nullable=False),
    sa.Column('expected_behaviour', sa.Text(), nullable=False),
    sa.Column('observed_behaviour', sa.Text(), nullable=False),
    sa.Column('evidence_refs', sa.JSON(), nullable=False),
    sa.Column('recommendation', sa.Text(), nullable=False),
    sa.Column('status', sa.Enum('NEW', 'REVIEWED', 'VALIDATED', 'DISMISSED', 'ESCALATED', 'CLOSED', name='findingstatus', native_enum=False), nullable=False),
    sa.Column('created_at', sa.DateTime(timezone=True), nullable=False),
    sa.Column('updated_at', sa.DateTime(timezone=True), nullable=False),
    sa.ForeignKeyConstraint(['analysis_run_id'], ['analysis_runs.id'], ondelete='CASCADE'),
    sa.ForeignKeyConstraint(['asset_id'], ['assets.id'], ondelete='CASCADE'),
    sa.ForeignKeyConstraint(['case_id'], ['cases.id'], ondelete='SET NULL'),
    sa.ForeignKeyConstraint(['cse_id'], ['cses.id'], ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index('idx_finding_cse_severity', 'findings', ['cse_id', 'severity'], unique=False)
    op.create_index('idx_finding_cse_status', 'findings', ['cse_id', 'status'], unique=False)
    op.create_index('idx_finding_priority', 'findings', ['supervisory_priority'], unique=False)
    op.create_index(op.f('ix_findings_analysis_run_id'), 'findings', ['analysis_run_id'], unique=False)
    op.create_index(op.f('ix_findings_asset_id'), 'findings', ['asset_id'], unique=False)
    op.create_index(op.f('ix_findings_case_id'), 'findings', ['case_id'], unique=False)
    op.create_index(op.f('ix_findings_created_at'), 'findings', ['created_at'], unique=False)
    op.create_index(op.f('ix_findings_cse_id'), 'findings', ['cse_id'], unique=False)
    op.create_index(op.f('ix_findings_rule_id'), 'findings', ['rule_id'], unique=False)
    op.create_index(op.f('ix_findings_severity'), 'findings', ['severity'], unique=False)
    op.create_index(op.f('ix_findings_status'), 'findings', ['status'], unique=False)
    op.create_index(op.f('ix_findings_supervisory_priority'), 'findings', ['supervisory_priority'], unique=False)
    op.create_table('risk_scores',
    sa.Column('id', app.models.base.GUID(length=36), nullable=False),
    sa.Column('cse_id', app.models.base.GUID(length=36), nullable=False),
    sa.Column('analysis_run_id', app.models.base.GUID(length=36), nullable=False),
    sa.Column('computed_at', sa.DateTime(timezone=True), nullable=False),
    sa.Column('total_score', sa.Float(), nullable=False),
    sa.Column('component_breakdown', sa.JSON(), nullable=False),
    sa.Column('rule_version', sa.String(length=50), nullable=False),
    sa.Column('model_version', sa.String(length=50), nullable=False),
    sa.Column('created_at', sa.DateTime(timezone=True), nullable=False),
    sa.Column('updated_at', sa.DateTime(timezone=True), nullable=False),
    sa.ForeignKeyConstraint(['analysis_run_id'], ['analysis_runs.id'], ondelete='CASCADE'),
    sa.ForeignKeyConstraint(['cse_id'], ['cses.id'], ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_risk_scores_analysis_run_id'), 'risk_scores', ['analysis_run_id'], unique=False)
    op.create_index(op.f('ix_risk_scores_computed_at'), 'risk_scores', ['computed_at'], unique=False)
    op.create_index(op.f('ix_risk_scores_created_at'), 'risk_scores', ['created_at'], unique=False)
    op.create_index(op.f('ix_risk_scores_cse_id'), 'risk_scores', ['cse_id'], unique=False)
    op.create_index(op.f('ix_risk_scores_total_score'), 'risk_scores', ['total_score'], unique=False)
    op.create_table('evidence',
    sa.Column('id', app.models.base.GUID(length=36), nullable=False),
    sa.Column('finding_id', app.models.base.GUID(length=36), nullable=False),
    sa.Column('evidence_type', sa.String(length=100), nullable=False),
    sa.Column('source_table', sa.String(length=100), nullable=False),
    sa.Column('source_record_id', sa.String(length=255), nullable=False),
    sa.Column('description', sa.Text(), nullable=False),
    sa.Column('captured_at', sa.DateTime(timezone=True), nullable=False),
    sa.Column('created_at', sa.DateTime(timezone=True), nullable=False),
    sa.Column('updated_at', sa.DateTime(timezone=True), nullable=False),
    sa.ForeignKeyConstraint(['finding_id'], ['findings.id'], ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_evidence_captured_at'), 'evidence', ['captured_at'], unique=False)
    op.create_index(op.f('ix_evidence_created_at'), 'evidence', ['created_at'], unique=False)
    op.create_index(op.f('ix_evidence_evidence_type'), 'evidence', ['evidence_type'], unique=False)
    op.create_index(op.f('ix_evidence_finding_id'), 'evidence', ['finding_id'], unique=False)
    op.create_table('investigations',
    sa.Column('id', app.models.base.GUID(length=36), nullable=False),
    sa.Column('alert_id', app.models.base.GUID(length=36), nullable=False),
    sa.Column('analyst_id', app.models.base.GUID(length=36), nullable=True),
    sa.Column('started_at', sa.DateTime(timezone=True), nullable=False),
    sa.Column('ended_at', sa.DateTime(timezone=True), nullable=True),
    sa.Column('duration_seconds', sa.Integer(), nullable=True),
    sa.Column('notes', sa.Text(), nullable=True),
    sa.Column('outcome', sa.String(length=100), nullable=True),
    sa.Column('created_at', sa.DateTime(timezone=True), nullable=False),
    sa.Column('updated_at', sa.DateTime(timezone=True), nullable=False),
    sa.ForeignKeyConstraint(['alert_id'], ['alerts.id'], ondelete='CASCADE'),
    sa.ForeignKeyConstraint(['analyst_id'], ['analysts.id'], ondelete='SET NULL'),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_investigations_alert_id'), 'investigations', ['alert_id'], unique=True)
    op.create_index(op.f('ix_investigations_analyst_id'), 'investigations', ['analyst_id'], unique=False)
    op.create_index(op.f('ix_investigations_created_at'), 'investigations', ['created_at'], unique=False)
    op.create_table('escalations',
    sa.Column('id', app.models.base.GUID(length=36), nullable=False),
    sa.Column('investigation_id', app.models.base.GUID(length=36), nullable=False),
    sa.Column('escalated_to', sa.String(length=100), nullable=False),
    sa.Column('escalated_at', sa.DateTime(timezone=True), nullable=False),
    sa.Column('reason', sa.Text(), nullable=True),
    sa.Column('created_at', sa.DateTime(timezone=True), nullable=False),
    sa.Column('updated_at', sa.DateTime(timezone=True), nullable=False),
    sa.ForeignKeyConstraint(['investigation_id'], ['investigations.id'], ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_escalations_created_at'), 'escalations', ['created_at'], unique=False)
    op.create_index(op.f('ix_escalations_investigation_id'), 'escalations', ['investigation_id'], unique=True)
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_index(op.f('ix_escalations_investigation_id'), table_name='escalations')
    op.drop_index(op.f('ix_escalations_created_at'), table_name='escalations')
    op.drop_table('escalations')
    op.drop_index(op.f('ix_investigations_created_at'), table_name='investigations')
    op.drop_index(op.f('ix_investigations_analyst_id'), table_name='investigations')
    op.drop_index(op.f('ix_investigations_alert_id'), table_name='investigations')
    op.drop_table('investigations')
    op.drop_index(op.f('ix_evidence_finding_id'), table_name='evidence')
    op.drop_index(op.f('ix_evidence_evidence_type'), table_name='evidence')
    op.drop_index(op.f('ix_evidence_created_at'), table_name='evidence')
    op.drop_index(op.f('ix_evidence_captured_at'), table_name='evidence')
    op.drop_table('evidence')
    op.drop_index(op.f('ix_risk_scores_total_score'), table_name='risk_scores')
    op.drop_index(op.f('ix_risk_scores_cse_id'), table_name='risk_scores')
    op.drop_index(op.f('ix_risk_scores_created_at'), table_name='risk_scores')
    op.drop_index(op.f('ix_risk_scores_computed_at'), table_name='risk_scores')
    op.drop_index(op.f('ix_risk_scores_analysis_run_id'), table_name='risk_scores')
    op.drop_table('risk_scores')
    op.drop_index(op.f('ix_findings_supervisory_priority'), table_name='findings')
    op.drop_index(op.f('ix_findings_status'), table_name='findings')
    op.drop_index(op.f('ix_findings_severity'), table_name='findings')
    op.drop_index(op.f('ix_findings_rule_id'), table_name='findings')
    op.drop_index(op.f('ix_findings_cse_id'), table_name='findings')
    op.drop_index(op.f('ix_findings_created_at'), table_name='findings')
    op.drop_index(op.f('ix_findings_case_id'), table_name='findings')
    op.drop_index(op.f('ix_findings_asset_id'), table_name='findings')
    op.drop_index(op.f('ix_findings_analysis_run_id'), table_name='findings')
    op.drop_index('idx_finding_priority', table_name='findings')
    op.drop_index('idx_finding_cse_status', table_name='findings')
    op.drop_index('idx_finding_cse_severity', table_name='findings')
    op.drop_table('findings')
    op.drop_index(op.f('ix_closures_created_at'), table_name='closures')
    op.drop_index(op.f('ix_closures_case_id'), table_name='closures')
    op.drop_table('closures')
    op.drop_index(op.f('ix_audit_logs_user_id'), table_name='audit_logs')
    op.drop_index(op.f('ix_audit_logs_timestamp'), table_name='audit_logs')
    op.drop_index(op.f('ix_audit_logs_entity_type'), table_name='audit_logs')
    op.drop_index(op.f('ix_audit_logs_entity_id'), table_name='audit_logs')
    op.drop_index(op.f('ix_audit_logs_dataset_import_id'), table_name='audit_logs')
    op.drop_index(op.f('ix_audit_logs_created_at'), table_name='audit_logs')
    op.drop_index(op.f('ix_audit_logs_analysis_run_id'), table_name='audit_logs')
    op.drop_index(op.f('ix_audit_logs_action'), table_name='audit_logs')
    op.drop_table('audit_logs')
    op.drop_index(op.f('ix_alerts_status'), table_name='alerts')
    op.drop_index(op.f('ix_alerts_severity'), table_name='alerts')
    op.drop_index(op.f('ix_alerts_cse_id'), table_name='alerts')
    op.drop_index(op.f('ix_alerts_created_at'), table_name='alerts')
    op.drop_index(op.f('ix_alerts_category'), table_name='alerts')
    op.drop_index(op.f('ix_alerts_asset_id'), table_name='alerts')
    op.drop_index('idx_alert_cse_severity_status', table_name='alerts')
    op.drop_index('idx_alert_created_at', table_name='alerts')
    op.drop_table('alerts')
    op.drop_index(op.f('ix_peer_group_memberships_created_at'), table_name='peer_group_memberships')
    op.drop_table('peer_group_memberships')
    op.drop_index(op.f('ix_data_quality_issues_severity'), table_name='data_quality_issues')
    op.drop_index(op.f('ix_data_quality_issues_issue_type'), table_name='data_quality_issues')
    op.drop_index(op.f('ix_data_quality_issues_dataset_import_id'), table_name='data_quality_issues')
    op.drop_index(op.f('ix_data_quality_issues_created_at'), table_name='data_quality_issues')
    op.drop_table('data_quality_issues')
    op.drop_index(op.f('ix_cases_status'), table_name='cases')
    op.drop_index(op.f('ix_cases_cse_id'), table_name='cases')
    op.drop_index(op.f('ix_cases_created_at'), table_name='cases')
    op.drop_table('cases')
    op.drop_index(op.f('ix_benchmarks_peer_group_id'), table_name='benchmarks')
    op.drop_index(op.f('ix_benchmarks_metric_name'), table_name='benchmarks')
    op.drop_index(op.f('ix_benchmarks_created_at'), table_name='benchmarks')
    op.drop_table('benchmarks')
    op.drop_index(op.f('ix_assets_status'), table_name='assets')
    op.drop_index(op.f('ix_assets_cse_id'), table_name='assets')
    op.drop_index(op.f('ix_assets_criticality'), table_name='assets')
    op.drop_index(op.f('ix_assets_created_at'), table_name='assets')
    op.drop_index('idx_asset_cse_criticality', table_name='assets')
    op.drop_table('assets')
    op.drop_index(op.f('ix_analysts_cse_id'), table_name='analysts')
    op.drop_index(op.f('ix_analysts_created_at'), table_name='analysts')
    op.drop_index('idx_analyst_cse_handle', table_name='analysts')
    op.drop_table('analysts')
    op.drop_index(op.f('ix_analysis_runs_status'), table_name='analysis_runs')
    op.drop_index(op.f('ix_analysis_runs_started_at'), table_name='analysis_runs')
    op.drop_index(op.f('ix_analysis_runs_rule_version_id'), table_name='analysis_runs')
    op.drop_index(op.f('ix_analysis_runs_model_version_id'), table_name='analysis_runs')
    op.drop_index(op.f('ix_analysis_runs_dataset_import_id'), table_name='analysis_runs')
    op.drop_index(op.f('ix_analysis_runs_created_at'), table_name='analysis_runs')
    op.drop_table('analysis_runs')
    op.drop_index(op.f('ix_rule_versions_version'), table_name='rule_versions')
    op.drop_index(op.f('ix_rule_versions_status'), table_name='rule_versions')
    op.drop_index(op.f('ix_rule_versions_rule_id'), table_name='rule_versions')
    op.drop_index(op.f('ix_rule_versions_created_at'), table_name='rule_versions')
    op.drop_table('rule_versions')
    op.drop_index(op.f('ix_peer_groups_name'), table_name='peer_groups')
    op.drop_index(op.f('ix_peer_groups_created_at'), table_name='peer_groups')
    op.drop_table('peer_groups')
    op.drop_index(op.f('ix_model_versions_version'), table_name='model_versions')
    op.drop_index(op.f('ix_model_versions_status'), table_name='model_versions')
    op.drop_index(op.f('ix_model_versions_model_name'), table_name='model_versions')
    op.drop_index(op.f('ix_model_versions_created_at'), table_name='model_versions')
    op.drop_table('model_versions')
    op.drop_index(op.f('ix_dataset_imports_status'), table_name='dataset_imports')
    op.drop_index(op.f('ix_dataset_imports_imported_at'), table_name='dataset_imports')
    op.drop_index(op.f('ix_dataset_imports_created_at'), table_name='dataset_imports')
    op.drop_table('dataset_imports')
    op.drop_index(op.f('ix_cses_sector'), table_name='cses')
    op.drop_index(op.f('ix_cses_name'), table_name='cses')
    op.drop_index(op.f('ix_cses_entity_type'), table_name='cses')
    op.drop_index(op.f('ix_cses_created_at'), table_name='cses')
    op.drop_table('cses')
    # ### end Alembic commands ###
